spring:
  datasource:
    url: jdbc:postgresql://db:5432/booking
    username: booking
    password: booking
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    show-sql: false

  flyway:
    locations: classpath:db/migration

logging:
  level:
    com.relix.servicebooking: INFO

jwt:
  secret: ${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3QgdG9rZW4gZ2VuZXJhdGlvbiB0aGF0IGlzIGF0IGxlYXN0IDI1NiBiaXRz}
