spring:
  datasource:
    url: jdbc:postgresql://db:5432/booking
    username: booking
    password: booking
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    show-sql: false

  flyway:
    locations: classpath:db/migration

logging:
  level:
    com.relix.servicebooking: INFO
