spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: booking
    password: booking
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    show-sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/seed

logging:
  level:
    com.relix.servicebooking: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3QgdG9rZW4gZ2VuZXJhdGlvbiB0aGF0IGlzIGF0IGxlYXN0IDI1NiBiaXRz
